### PR TITLE
fix setting lz4 compression levels

### LINKED ISSUE #778: Unable to specify LZ4 compression level
CompressionCoded.WithLevel casts its argument to byte and maxes out at 127. - https://github.com/twmb/franz-go/blob/a5f2b710830e32fc3f90374be47ec59849807342/pkg/kgo/compression.go#L71

However, LZ4 compression levels are much larger than that - https://github.com/pierrec/lz4/blob/v4/options.go#L155 - they are defined as 0, 512, 1024, ... , 131072.

Specifying LZ4 compression level in franz-go therefore will always result in the default.

### PR DESCRIPTION
**Pull request by asg0451**
resolves #778

### CODE REVIEW

**Comment by twmb** [comment]
Thanks!

**Review by twmb — DISMISSED** [review]

**Comment by asg0451** [comment]
@twmb am i good to merge here?

**Comment by twmb** [comment]
I want to get this in the next patch release but can't figure out why #785 is failing (which is important to get in, probably the most important bug at the moment)

**Comment by twmb** [comment]
Typo, I mean #786. If you're able to figure out the CI problem, that'd be great :D

**Comment by asg0451** [comment]
ok, i'll hold off. that pr looks like ci is passing to me though?

**Comment by twmb** [comment]
Wow, typo twice. I'm going to delete my prior comments. #787 is the one that's failing.

**Comment by asg0451** [comment]
gotcha. not sure if i really have the bandwidth to debug that at the moment ;)

btw if i may ask, do these new race-y bugs affect the integration i just merged into cockroachdb? will we need to upgrade to fix this (once you fix it of course) before it makes it into a new release? we produce concurrently with max buffered records set, not bytes.

**Comment by twmb** [comment]
The data race is largely non impactful (it's actually existed for a really long time, it's really hard to trigger, and at the architecture level, you're not going to see a partial write).

The #787 is worrying, but it only affects people that use MaxBufferedBytes. I don't think you do, it's a fairly new option and I don't expect most people to use it.

**Comment by asg0451** [comment]
(if you want to move this discussion to another venue that's fine, lmk)

> at the architecture level, you're not going to see a partial write
can you expand on this? what would the result be both downstream and in the running process

**Comment by twmb** [comment]
The data race is a read/write problem on a boolean. The standard problem with read/write races is that the reader experiences a partial read -- e.g. I'm writing "foobar" and the underlying data says "hacked", the reader reads "fooked" (half of foobar, half of hacked). No CPU architecture actually does a partial write of a boolean sized field.

The other problem is that compilers and CPUs can reorder where the read happens, but Go uses seqcst for any atomic operation, and there are atomic operations before and after the reading of this bool. So, this bool isn't being reordered to a place that it really matters.

The last worry here is that _what_ this field is for isn't working properly. This field is meant to guard failing records if we don't know it's safe. There's a related open issue about this (not the bug, but "why was this hanging") where you can see what safe is, here: https://github.com/twmb/franz-go/issues/769#issuecomment-2235707417

So, if a race happens and what the bool is guarding isn't effectively guarded, what you'll see in your application is OutOfOrderSequenceNumber errors and you'll need to restart your client. This chunk of code has existed for 3yr and so far nobody has reported unexpected OOOSN errors.

**Comment by asg0451** [comment]
gotcha. thanks for the context and the responsiveness!

**Pull request merged**
