### PR TITLE
new plugin klogr: adding support for go-logr/logr within kgo.WithLogger per issue #237

### PR DESCRIPTION
**Pull request by twmb**

### CODE REVIEW

**Comment by twmb** [comment]
@rmb938 would it be possible for you to review if [this small file](https://github.com/twmb/franz-go/pull/308/files#diff-b6a548b6438ac6e803cddb6af11456edf787597edd9d579cac7ebe17db9bb258R1-R41) is correct per your feature request? If so, I can take ownership of any modifications and merge / release.

**Comment by rmb938** [comment]
Ah you found @afitterer3000's commit, they are one of my co-workers.

That file is correct per my request but I don't believe we actually got it working correctly. Sadly it got pushed back in our backlog so we haven't had time to properly finish development of it and test :(

**Comment by twmb** [comment]
o i c, I jumped the gun on that then 😅
I saw the fork, which PR'd against itself and figured perhaps it was meant to PR against this repo. I'll close this PR for now then!

**Comment by rmb938** [comment]
Haha no problem! Always glad to see an active project owner :)

Our backlog is most likely going to be freeing up by the end of the month
so hoping to have something for you by then. At least if someone else
doesn't beat us to it.

**Pull request closed without merging**
