### PR TITLE
kotel update metric package

### PR DESCRIPTION
**Pull request by brennan-airtime**
`syncint64` was removed which means the `kotel` plugin cannot be used if using `go.opentelemetry.io/otel/metric >= 0.36.0`

### CODE REVIEW

**Review by twmb — APPROVED** [review]

**Comment by twmb** [comment]
Looking at the godoc, the APIs were deprecated but not removed, but I can take this as a patch anyway.

**Comment by twmb** [comment]
https://github.com/twmb/franz-go/releases/tag/plugin%2Fkotel%2Fv1.0.1

**Comment by brennan-airtime** [comment]
The last version the package is available in is 0.35.0, it is no longer available in 0.36.0.

https://pkg.go.dev/go.opentelemetry.io/otel/metric/instrument/syncint64

You can also see in the release notes:

https://github.com/open-telemetry/opentelemetry-go/releases/tag/v1.13.0

Copied here for posterity

```
Removed
The deprecated go.opentelemetry.io/otel/metric/instrument/asyncfloat64 package is removed. (https://github.com/open-telemetry/opentelemetry-go/pull/3631)
The deprecated go.opentelemetry.io/otel/metric/instrument/asyncint64 package is removed. (https://github.com/open-telemetry/opentelemetry-go/pull/3631)
The deprecated go.opentelemetry.io/otel/metric/instrument/syncfloat64 package is removed. (https://github.com/open-telemetry/opentelemetry-go/pull/3631)
The deprecated go.opentelemetry.io/otel/metric/instrument/syncint64 package is removed. (https://github.com/open-telemetry/opentelemetry-go/pull/3631)
```

**Comment by brennan-airtime** [comment]
Thanks for the quick turnaround.

**Comment by twmb** [comment]
Hm I must’ve looked at something incorrectly, I went to the package itself
on pkg.go.dev where it said the APIs were deprecated, but didn’t look at
version numbers.

No worries though, not using deprecated or removed APIs is preferable :)

**Comment by brennan-airtime** [comment]
Oh yeah, I also wanted to make sure I wasn't mistaken.

**Pull request merged**
