### PR TITLE
fetches: add IsContextCanceled helper

### PR DESCRIPTION
**Pull request by dwagin**
What do you say about such an helper?

### CODE REVIEW

**Comment by dwagin** [comment]
or maybe add a helper function that returns the first error?

**Comment by un000** [comment]
> or maybe add a helper function that returns the first error?

@dwagin fetches have .Err() method which returns the first error.

**Comment by dwagin** [comment]
> > or maybe add a helper function that returns the first error?
> 
> @dwagin fetches have .Err() method which returns the first error.

@un000 `.Err()` iterate over all fetches

**Comment by un000** [comment]
> > > or maybe add a helper function that returns the first error?
> > 
> > 
> > @dwagin fetches have .Err() method which returns the first error.
> 
> @un000 `.Err()` iterate over all fetches

It iterates, but returns a first error.
If Poll* dies by ctx.Done(), then Poll* returns a fake topic with ctx.Err().

https://github.com/twmb/franz-go/blob/f981856e89c99898aa0c86a7f463d733b1753c64/pkg/kgo/consumer.go#L400-L405

https://github.com/twmb/franz-go/blob/f981856e89c99898aa0c86a7f463d733b1753c64/pkg/kgo/consumer.go#L335-L345

**Comment by dwagin** [comment]
@un000 Thanks, I've already looked at this.

**Comment by twmb** [comment]
I'm not sure how this is meaningfully different from `Err` -- in what context would `OnlyError` be used where `Err` couldn't be?

**Comment by dwagin** [comment]
For example current poll() implementation:

```go
func fetchesOnlyError(fs kgo.Fetches) error {
	if len(fs) == 1 && len(fs[0].Topics) == 1 && len(fs[0].Topics[0].Partitions) == 1 {
		return fs[0].Topics[0].Partitions[0].Err
	}
	return nil
}

func (k *Kafka) poll() {
	defer k.wg.Done()
	defer k.client.Close()

	for {
		select {
		case <-k.ctx.Done():
			return

		default:
			fs := k.client.PollFetches(k.ctx)
			if err := fetchesOnlyError(fs); err != nil && (errors.Is(err, kgo.ErrClientClosed) || errors.Is(err, context.Canceled)) {
				return
			}
			var errs []kgo.FetchError
			fs.EachTopic(func(ft kgo.FetchTopic) {
				var (
					ok bool
					p  map[int32]Consumer
					c  Consumer
				)

				k.consumersMu.Lock()
				defer k.consumersMu.Unlock()
				if p, ok = k.consumers[ft.Topic]; ok {
					ft.EachPartition(func(fp kgo.FetchPartition) {
						if fp.Err != nil {
							errs = append(errs, kgo.FetchError{
								Topic:     ft.Topic,
								Partition: fp.Partition,
								Err:       fp.Err,
							})
							return
						}

						if c, ok = p[fp.Partition]; ok {
							c.PushMessage(fp.Records)
						} else {
							k.Log().
								WithFields(log.Fields{"topic": ft.Topic}).
								WithFields(log.Fields{"partition": fp.Partition}).
								Error("Consumer for partition does not exist")
							k.exit()
						}
					})
				} else {
					k.Log().
						WithFields(log.Fields{"topic": ft.Topic}).
						Error("Consumer for topic does not exist")
					k.exit()
				}
			})
			if len(errs) > 0 {
				for _, e := range errs {
					k.Log().
						WithFields(log.Fields{"topic": e.Topic}).
						WithFields(log.Fields{"partition": e.Partition}).
						Error(e.Err)
				}
				k.exit()
				return
			}
		}
	}
}

```

**Comment by un000** [comment]
@dwagin you could check `fs.Err()` here and nothing will change.

**Comment by dwagin** [comment]
> @dwagin you could check `fs.Err()` here and nothing will change.

Compare the performance, the difference is 6-7x.

**Comment by dwagin** [comment]
```go
package kafka_test

import (
	"context"
	"errors"
	"testing"

	"github.com/twmb/franz-go/pkg/kgo"
)

var data = kgo.Fetches{{
	Topics: []kgo.FetchTopic{
		{
			Topic: "",
			Partitions: []kgo.FetchPartition{
				{
					Partition: 0,
					Err:       nil,
				},
				{
					Partition: 0,
					Err:       nil,
				},
				{
					Partition: 0,
					Err:       nil,
				},
				{
					Partition: 0,
					Err:       nil,
				},
				{
					Partition: 0,
					Err:       nil,
				},
				{
					Partition: 0,
					Err:       nil,
				},
			},
		},
	},
}}

func fetchesOnlyError(fs kgo.Fetches) error {
	if len(fs) == 1 && len(fs[0].Topics) == 1 && len(fs[0].Topics[0].Partitions) == 1 {
		return fs[0].Topics[0].Partitions[0].Err
	}
	return nil
}

func BenchmarkOnlyError(b *testing.B) {
	for i := 0; i < b.N; i++ {
		if err := fetchesOnlyError(data); err != nil && (errors.Is(err, kgo.ErrClientClosed) || errors.Is(err, context.Canceled)) {
			return
		}
	}
}

func BenchmarkErr(b *testing.B) {
	for i := 0; i < b.N; i++ {
		if err := data.Err(); err != nil && (errors.Is(err, kgo.ErrClientClosed) || errors.Is(err, context.Canceled)) {
			return
		}
	}
}

```

**Comment by twmb** [comment]
This has been released in v1.7.0

**Pull request closed without merging**
